### ISSUE TITLE
Please support Loop dev

### ISSUE THREAD

**Issue by creepymonster** [julian-groen/LibreKit#1]
What is necessary to use the CGM Manager in Loop dev. I tried to create the corresponding plugin project - but my Xcode skills are not sufficient for that.

Many greetings
Reimar

**Comment by julian-groen** [comment]
Hi,

I am currently refactoring and updating all the code for Loop Dev. I hope to finish this for the end of this month (currently busy with school). I will notify you when I'm finished!

**Comment by creepymonster** [comment]
Thank you very much, I don't want to put any pressure on you. I am happy to receive your notification.
